### ISSUE TITLE
Adopt config from other Testing Library repos

### ISSUE THREAD

**Issue by nickserv** [testing-library/testing-library-recorder-extension#13]
I'm basing this work off [dom-testing-library](https://github.com/testing-library/dom-testing-library) because of https://github.com/kentcdodds/generator-kcd-oss/issues/55.
- [x] Funding via GitHub Sponsors
- [x] MIT License
- [x] Prettier
- [x] Docs
- [x] [Badges](https://shields.io/)

**Comment by nickserv** [comment]
The Prettier setup got released on its own since code generation changes are technically a breaking change.

**Comment by nickmccurdy** [comment]
- #20
