### ISSUE TITLE
Support copy single step as Testing library script

### ISSUE THREAD

**Issue by jecfish** [testing-library/testing-library-recorder-extension#29]
Chrome 109 launches a new "Copy a single step as script" feature. 

**How to test**
- In a recording, right click on a step, select copy as [your extension] script option. 

**Action required**
- Your extension needs to implement the [stringifyStep](https://developer.chrome.com/docs/extensions/reference/devtools_recorder/#examples) API for this feature to work.
- You can test this feature with the latest Chrome Canary

<img width="1131" alt="recorder-copy" src="https://user-images.githubusercontent.com/5917927/200954152-6c1f106b-8006-4cba-9c12-1967703e917a.png">

I briefly tested the extension, seems like it already handle `stringifyStep` properly. Please give it a test!

**Comment by jecfish** [comment]
@nickmccurdy FYI!

**Comment by nickserv** [comment]
Thanks for the reminder, but I've already implemented this earlier using `stringifyStep`. Now that Chrome 109 is out, I'm also documenting it.
